Oriana\Orders\Domain\Model\Order\Order:
  type: entity
  table: orders
  repositoryClass: Oriana\Orders\Infrastructure\Domain\Model\Order\DoctrineOrderRepository
  id:
    id:
      column: id
      type: OrderId
  fields:
    date:
      type: date
      column: creation_date
    clientId:
      type: ClientId
      column: client_id
  manyToMany:
    orderItems:
      orphanRemoval: true
      cascade: ["all"]
      targetEntity: OrderItem
      joinTable:
        name: Order_Items
        joinColumns:
          order_id:
            referencedColumnName: id
        inverseJoinColumns:
          item_id:
            referencedColumnName: id
            unique: true